# Generated by Django 5.2.8 on 2025-12-07 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_student_interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='age',
        ),
        migrations.AddField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='female', max_length=20),
            preserve_default=False,
        ),
    ]
