# Generated by Django 5.2.8 on 2025-12-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_student_interface', '0002_remove_child_age_child_date_of_birth_child_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad'), ('unsure', 'Unsure')], max_length=20, null=True),
        ),
    ]
