# Generated by Django 5.2.8 on 2025-12-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_student_interface', '0003_activitylog_notes_activitylog_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad'), ('neutral', 'Neutral')], max_length=20, null=True),
        ),
    ]
