# Generated by Django 5.2.8 on 2025-12-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_student_interface', '0004_alter_activitylog_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedactivity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recommendedactivity',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendedactivity',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('too_hard', 'Too Hard')], max_length=20, null=True),
        ),
    ]
