# Generated by Django 5.2.8 on 2025-12-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_student_interface', '0005_recommendedactivity_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedactivity',
            name='deactivation_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('too_hard', 'Too Hard'), ('too_easy', 'Too Easy')], max_length=20, null=True),
        ),
    ]
