# Generated by Django 5.2.8 on 2025-12-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_student_interface', '0006_alter_recommendedactivity_deactivation_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='committedactivity',
            options={'verbose_name_plural': 'Committed activities'},
        ),
    ]
