# Generated by Django 5.2.8 on 2025-11-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_student_interface', '0007_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendedCourse',
        ),
    ]
