# Generated by Django 5.2.8 on 2025-12-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_student_interface', '0008_delete_recommendedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='committedactivity',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
