#!/usr/bin/env bash
# claude.sh — Generated by fls plugin init
# Launches Claude Code with the FLS plugin loaded.

FLS_PATH="__FLS_PATH__"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

FLS_PLUGIN=1 claude --plugin-dir "$SCRIPT_DIR/$FLS_PATH/fls-claude-plugin" "$@"
