#!/bin/bash
# dev_db_init.sh — Generated by fls plugin init
# Customize the "Project-specific setup" section below.

# FLS_PATH is set during `fls:init` to the path where FLS is installed
# (e.g., "submodules/Freedom-LS" for concrete implementations, or "." for FLS itself)
FLS_PATH="__FLS_PATH__"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PLUGIN_DIR="$SCRIPT_DIR/$FLS_PATH/fls-claude-plugin"

# === FLS base setup ===
"$PLUGIN_DIR/scripts/dev_db_init.sh" "$@"

# === Project-specific setup ===
# Add your implementation-specific steps below:
