# Generated by Django 6.0.4 on 2026-10-08 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMessagingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner_to_educator', models.CharField(choices=[('inherit', 'Inherit'), ('open', 'Open'), ('closed', 'Closed')], default='inherit', help_text='"Inherit" uses the next level up.', max_length=7)),
                ('learner_to_cohort_peer', models.CharField(choices=[('inherit', 'Inherit'), ('open', 'Open'), ('closed', 'Closed')], default='inherit', help_text='"Inherit" uses the next level up.', max_length=7)),
                ('learner_to_course_peer', models.CharField(choices=[('inherit', 'Inherit'), ('open', 'Open'), ('closed', 'Closed')], default='inherit', help_text='"Inherit" uses the next level up.', max_length=7)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('learner_to_educator__in', ['inherit', 'open', 'closed'])), name='sitemessagingconfig_learner_to_educator_is_a_messaging_flag'), models.CheckConstraint(condition=models.Q(('learner_to_cohort_peer__in', ['inherit', 'open', 'closed'])), name='sitemessagingconfig_learner_to_cohort_peer_is_a_messaging_flag'), models.CheckConstraint(condition=models.Q(('learner_to_course_peer__in', ['inherit', 'open', 'closed'])), name='sitemessagingconfig_learner_to_course_peer_is_a_messaging_flag'), models.UniqueConstraint(fields=('site',), name='unique_messaging_config_per_site')],
            },
        ),
    ]
