# Generated by Django 6.0.4 on 2026-10-08 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_learner_management', '0004_alter_cohort_options_alter_learner_options'),
        ('freedom_ls_messaging_policy', '0002_cohortmessagingconfig_organisationmessagingconfig'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortCourseRegistrationMessagingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner_to_course_peer', models.CharField(choices=[('inherit', 'Inherit'), ('open', 'Open'), ('closed', 'Closed')], default='inherit', help_text='"Inherit" uses the next level up.', max_length=7)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_config', to='freedom_ls_learner_management.cohortcourseregistration')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('learner_to_course_peer__in', ['inherit', 'open', 'closed'])), name='cohort_course_registration_messaging_config_flag_is_a_messaging_flag')],
            },
        ),
        migrations.CreateModel(
            name='LearnerCourseRegistrationMessagingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner_to_course_peer', models.CharField(choices=[('inherit', 'Inherit'), ('open', 'Open'), ('closed', 'Closed')], default='inherit', help_text='"Inherit" uses the next level up.', max_length=7)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_config', to='freedom_ls_learner_management.learnercourseregistration')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('learner_to_course_peer__in', ['inherit', 'open', 'closed'])), name='learner_course_registration_messaging_config_flag_is_a_messaging_flag')],
            },
        ),
        migrations.CreateModel(
            name='LearnerMessagingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner_to_educator', models.CharField(choices=[('inherit', 'Inherit'), ('open', 'Open'), ('closed', 'Closed')], default='inherit', help_text='"Inherit" uses the next level up.', max_length=7)),
                ('learner_to_cohort_peer', models.CharField(choices=[('inherit', 'Inherit'), ('open', 'Open'), ('closed', 'Closed')], default='inherit', help_text='"Inherit" uses the next level up.', max_length=7)),
                ('learner_to_course_peer', models.CharField(choices=[('inherit', 'Inherit'), ('open', 'Open'), ('closed', 'Closed')], default='inherit', help_text='"Inherit" uses the next level up.', max_length=7)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_config', to='freedom_ls_learner_management.learner')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('learner_to_educator__in', ['inherit', 'open', 'closed'])), name='learnermessagingconfig_learner_to_educator_is_a_messaging_flag'), models.CheckConstraint(condition=models.Q(('learner_to_cohort_peer__in', ['inherit', 'open', 'closed'])), name='learnermessagingconfig_learner_to_cohort_peer_is_a_messaging_flag'), models.CheckConstraint(condition=models.Q(('learner_to_course_peer__in', ['inherit', 'open', 'closed'])), name='learnermessagingconfig_learner_to_course_peer_is_a_messaging_flag')],
            },
        ),
    ]
