# Generated by Django 6.0.4 on 2026-10-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_messaging_policy', '0003_cohortcourseregistrationmessagingconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemessagingconfig',
            name='offered_educator_roles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
