# Generated by Django 5.2.7 on 2025-11-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formprogress',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='topicprogress',
            old_name='site_id',
            new_name='site',
        ),
    ]
