# Generated by Django 5.2.7 on 2025-11-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formprogress',
            name='scores',
            field=models.JSONField(blank=True, help_text='Calculated scores by category', null=True),
        ),
    ]
