# Generated by Django 5.2.7 on 2025-11-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_interface', '0002_rename_site_id_formprogress_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='last_accessed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
