# Generated by Django 5.2.8 on 2025-12-14 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSignupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_signups', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site',), name='unique_signup_policy_per_site')],
            },
        ),
    ]
