# Generated by Django 5.2.7 on 2025-11-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_sites_user_site_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='site_id',
            new_name='site',
        ),
    ]
