# Generated by Django 6.0.4 on 2026-10-08 17:21

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freedom_ls_learner_management', '0004_alter_cohort_options_alter_learner_options'),
        ('freedom_ls_organisations', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='freedom_ls_organisations.organisation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_titles', to='freedom_ls_organisations.organisation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='freedom_ls_organisations.organisation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearnerHRAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organisation_start_date', models.DateField(blank=True, null=True)),
                ('job_title_start_date', models.DateField(blank=True, null=True)),
                ('department_start_date', models.DateField(blank=True, null=True)),
                ('location_start_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learner_hr_attributes', to='freedom_ls_hr_attributes.department')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learner_hr_attributes', to='freedom_ls_hr_attributes.jobtitle')),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_attributes', to='freedom_ls_learner_management.learner')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learner_hr_attributes', to='freedom_ls_hr_attributes.location')),
            ],
            options={
                'verbose_name': 'HR attributes',
                'verbose_name_plural': 'HR attributes',
            },
        ),
        migrations.CreateModel(
            name='OrganisationHRSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_rules_enabled', models.BooleanField(default=False)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_settings', to='freedom_ls_organisations.organisation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'HR settings',
                'verbose_name_plural': 'HR settings',
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('site'), models.F('organisation'), name='unique_department_name_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='jobtitle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('site'), models.F('organisation'), name='unique_job_title_name_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('site'), models.F('organisation'), name='unique_location_name_per_organisation'),
        ),
    ]
