#!/bin/bash
# dev_db_init.sh — Generated by the fls-dev plugin init
# Customize the "Project-specific setup" section below.

# PLUGINS_ROOT is set during `fls-dev:init` to the relative path from the project
# root to the checkout that holds `claude_plugins/` (default "." — the project root).
PLUGINS_ROOT="__PLUGINS_ROOT__"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
PLUGIN_DIR="$PROJECT_ROOT/$PLUGINS_ROOT/claude_plugins/fls-dev-claude-plugin"

# === FLS base setup ===
"$PLUGIN_DIR/scripts/dev_db_init.sh" "$@"

# === Project-specific setup ===
# Add your implementation-specific steps below:
