#!/bin/bash
# install_dev.sh — Generated by fls plugin init
# Customize the "Project-specific setup" section below.

# FLS_PATH is set during `fls:init` to the path where FLS is installed
# (e.g., "submodules/Freedom-LS" for concrete implementations, or "." for FLS itself)
FLS_PATH="."
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
PLUGIN_DIR="$PROJECT_ROOT/$FLS_PATH/fls-claude-plugin"

# === FLS base setup ===
"$PLUGIN_DIR/scripts/install_dev.sh" "$@"

# === Project-specific setup ===
# Add your implementation-specific steps below:
# === Project-specific setup ===
claude mcp add playwright npx '@playwright/mcp@latest'

# Create demo data (all sites)
uv run manage.py create_demo_data
python manage.py content_save ./demo_content DemoDev
