#!/bin/bash
# qa_collect_screenshots.sh — Generated by the fls-dev plugin init
# Customize the "Project-specific setup" section below.

# PLUGINS_ROOT is set during `fls-dev:init` to the relative path from the project root
# to the checkout that holds `claude_plugins/` (default "." — the project root itself).
PLUGINS_ROOT="."
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
PLUGIN_DIR="$PROJECT_ROOT/$PLUGINS_ROOT/claude_plugins/fls-dev"

# === Base setup ===
"$PLUGIN_DIR/scripts/qa_collect_screenshots.sh" "$@"

# === Project-specific setup ===
# Add your implementation-specific steps below:
