#!/bin/bash
# qa_collect_screenshots.sh — Generated by the fls-dev plugin init
# Customize the "Project-specific setup" section below.

set -euo pipefail

# PLUGINS_ROOT is set during `fls-dev:init` to the relative path from the project root
# to the checkout that holds `claude_plugins/` (default "." — the project root itself).
PLUGINS_ROOT="."
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
PLUGIN_DIR="$PROJECT_ROOT/$PLUGINS_ROOT/claude_plugins/fls-dev"

# CLAUDE_PROJECT_DIR is not reliably exported into the Bash tool environment, but
# the canonical script requires it. Derive it from this wrapper's known location
# (the project root is three levels up from this script's directory) when unset.
: "${CLAUDE_PROJECT_DIR:=$(readlink -f "$PROJECT_ROOT")}"
export CLAUDE_PROJECT_DIR

# === Base setup ===
"$PLUGIN_DIR/scripts/qa_collect_screenshots.sh" "$@"

# === Project-specific setup ===
# Add your implementation-specific steps below:
