# Generated by Django 5.2.9 on 2026-02-19 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('freedom_ls_student_management', '0002_cohortdeadline'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('is_hard_deadline', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('student_course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='freedom_ls_student_management.studentcourseregistration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('student_course_registration', 'content_type', 'object_id'), name='unique_student_deadline_per_item')],
            },
        ),
    ]
