# Generated by Django 5.2.9 on 2026-02-19 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('freedom_ls_student_management', '0003_studentdeadline'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCohortDeadlineOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('is_hard_deadline', models.BooleanField(default=True)),
                ('cohort_course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_overrides', to='freedom_ls_student_management.cohortcourseregistration')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_deadline_overrides', to='freedom_ls_student_management.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('cohort_course_registration', 'student', 'content_type', 'object_id'), name='unique_student_cohort_override_per_item')],
            },
        ),
    ]
