# Generated by Django 5.2.9 on 2026-03-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_student_management', '0009_remove_student_fk_make_user_non_nullable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
