# Generated by Django 5.2.9 on 2026-03-07 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0006_alter_activity_category_alter_activity_content_and_more'),
        ('freedom_ls_student_management', '0011_rename_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseregistration',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_registrations', to='freedom_ls_content_engine.course'),
        ),
    ]
