# Generated by Django 6.0.4 on 2026-08-11 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_organisations', '0001_initial'),
        ('freedom_ls_student_management', '0013_cohortmembership_unique_user_cohort_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='freedom_ls_organisations.organisation'),
        ),
        migrations.AddField(
            model_name='usercourseregistration',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='freedom_ls_organisations.organisation'),
        ),
    ]
