# Generated by Django 6.0.4 on 2026-08-11 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_organisations', '0001_initial'),
        ('freedom_ls_student_management', '0016_validate_organisation_backfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='freedom_ls_organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='usercourseregistration',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='freedom_ls_organisations.organisation'),
        ),
    ]
