# Generated by Django 5.2.7 on 2025-11-07 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Client application name', max_length=200)),
                ('api_key', models.CharField(editable=False, help_text='API key for authentication', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this client is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'API Client',
                'verbose_name_plural': 'API Clients',
            },
        ),
    ]
