# Generated by Django 6.0.4 on 2026-08-28 18:44

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import encrypted_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('description', models.CharField(max_length=200)),
                ('secret', models.CharField(editable=False, max_length=128)),
                ('event_types', models.JSONField(default=list)),
                ('http_method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='', max_length=7)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('headers_template', models.TextField(blank=True, default='')),
                ('body_template', models.TextField(blank=True, default='')),
                ('auth_type', models.CharField(choices=[('signing', 'HMAC Signing (Standard)'), ('none', 'None (Custom Auth via Headers)')], default='signing', max_length=10)),
                ('preset_slug', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='User intent: toggled by admin enable/disable actions only.')),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('disabled_at', models.DateTimeField(blank=True, help_text='Circuit breaker state: set when failure threshold is reached, cleared on successful delivery.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint_url', models.URLField(max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('permanent_failure', 'Permanent Failure'), ('dead_letter', 'Dead letter')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('last_response_body', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('last_response_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='freedom_ls_webhooks.webhookendpoint')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='freedom_ls_webhooks.webhookevent')),
            ],
            options={
                'verbose_name_plural': 'Webhook deliveries',
            },
        ),
        migrations.CreateModel(
            name='WebhookSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must start with a letter or underscore and contain only letters, digits, and underscores.', regex='^[a-zA-Z_][a-zA-Z0-9_]*$')])),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('encrypted_value', encrypted_fields.fields.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=django.contrib.postgres.indexes.GinIndex(fields=['event_types'], name='webhook_event_types_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'endpoint'), name='uniq_delivery_event_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='webhooksecret',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_webhook_secret_name_per_site'),
        ),
    ]
