# Generated by Django 6.0.3 on 2026-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookdelivery',
            options={'verbose_name_plural': 'Webhook deliveries'},
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='last_response_error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
