# Generated by Django 6.0.3 on 2026-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_alter_webhookdelivery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='secret',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
