# Generated by Django 6.0.3 on 2026-03-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_alter_webhookendpoint_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('permanent_failure', 'Permanent Failure'), ('dead_letter', 'Dead letter')], default='pending', max_length=20),
        ),
    ]
