# Generated by Django 6.0.3 on 2026-03-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_alter_webhookdelivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='disabled_at',
            field=models.DateTimeField(blank=True, help_text='Circuit breaker state: set when failure threshold is reached, cleared on successful delivery.', null=True),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='is_active',
            field=models.BooleanField(default=True, help_text='User intent: toggled by admin enable/disable actions only.'),
        ),
    ]
