# Generated by Django 6.0.3 on 2026-03-16 15:42

import django.core.validators
import django.db.models.deletion
import encrypted_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('webhooks', '0005_alter_webhookendpoint_disabled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must start with a letter or underscore and contain only letters, digits, and underscores.', regex='^[a-zA-Z_][a-zA-Z0-9_]*$')])),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('encrypted_value', encrypted_fields.fields.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'unique_together': {('site', 'name')},
            },
        ),
    ]
