# Generated by Django 6.0.3 on 2026-03-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_webhooksecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='auth_type',
            field=models.CharField(choices=[('signing', 'HMAC Signing (Standard)'), ('none', 'None (Custom Auth via Headers)')], default='signing', max_length=10),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='body_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='headers_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='http_method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='preset_slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
