# Generated by Django 6.0.3 on 2026-03-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_webhookendpoint_auth_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookendpoint',
            name='body_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='headers_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='http_method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='webhookendpoint',
            name='preset_slug',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
