# Generated by Django 6.0.3 on 2026-03-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0008_alter_webhookendpoint_body_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('permanent_failure', 'Permanent Failure'), ('dead_letter', 'Dead letter')], db_index=True, default='pending', max_length=20),
        ),
    ]
