# Generated by Django 6.0.4 on 2026-07-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('webhooks', '0009_alter_webhookdelivery_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'endpoint'), name='uniq_delivery_event_endpoint'),
        ),
    ]
