# Generated by Django 6.0.4 on 2026-08-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0010_webhookdelivery_uniq_delivery_event_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='endpoint_url',
            field=models.URLField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='endpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='webhooks.webhookendpoint'),
        ),
    ]
