# Generated by Django 6.0.4 on 2026-08-28 17:24

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('webhooks', '0011_webhookdelivery_endpoint_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webhooksecret',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=django.contrib.postgres.indexes.GinIndex(fields=['event_types'], name='webhook_event_types_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddConstraint(
            model_name='webhooksecret',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_webhook_secret_name_per_site'),
        ),
    ]
