# Generated by Django 5.2.7 on 2025-11-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohort',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='cohortmembership',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='site_id',
            new_name='site',
        ),
    ]
