# Generated by Django 5.2.7 on 2025-10-05 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sites',
        ),
        migrations.AddField(
            model_name='user',
            name='site_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
            preserve_default=False,
        ),
    ]
