# Generated by Django 5.2.8 on 2025-11-15 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_student_interface', '0002_child_user'),
        ('sites', '0002_alter_domain_unique'),
        ('student_progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ChildFormProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloom_student_interface.child')),
                ('form_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_progress.formprogress')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
