# Generated by Django 5.2.8 on 2025-11-25 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom_student_interface', '0004_contentrecommendation'),
        ('content_engine', '0006_activity_category'),
        ('sites', '0002_alter_domain_unique'),
        ('student_progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='content_engine.activity')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_activities', to='bloom_student_interface.child')),
                ('form_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_progress.formprogress')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name_plural': 'Recommended activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='content_engine.contentcollection')),
                ('form_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_progress.formprogress')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recommended courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ContentRecommendation',
        ),
    ]
