# Generated by Django 6.0.4 on 2026-08-24 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=500)),
                ('content', models.TextField(blank=True, default='', help_text='Markdown content')),
                ('strategy', models.CharField(choices=[('CATEGORY_VALUE_SUM', 'Category Value Sum'), ('QUIZ', 'Quiz')], max_length=50)),
                ('quiz_show_incorrect', models.BooleanField(blank=True, null=True)),
                ('quiz_pass_percentage', models.PositiveSmallIntegerField(blank=True, help_text='Percentage (0-100) required to pass the quiz', null=True)),
                ('submit_on_exit', models.BooleanField(default=False, help_text='If True, leaving the test mid-attempt finalises and scores it. If False (default), the attempt is saved and can be resumed.')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='freedom_ls_form_engine.form')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('form_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_items', to='freedom_ls_form_engine.formpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('checkboxes', 'Checkboxes'), ('short_text', 'Short Text'), ('long_text', 'Long Text')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('form_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='freedom_ls_form_engine.formpage')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='freedom_ls_form_engine.formquestion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
