# Generated by Django 6.0.4 on 2026-09-08 08:53

import django.db.models.deletion
import freedom_ls.form_engine.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_form_engine', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='strategy',
            field=models.CharField(choices=[('CATEGORY_VALUE_SUM', 'Category Value Sum'), ('QUIZ', 'Quiz'), ('UNSCORED', 'Unscored')], max_length=50),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('checkboxes', 'Checkboxes'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('number', 'Number'), ('file_upload', 'File upload')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuestionAnswerFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=freedom_ls.form_engine.models.get_user_uploads_storage, upload_to=freedom_ls.form_engine.models.question_answer_file_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_file', to='freedom_ls_form_engine.questionanswer')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
