# Generated by Django 6.0.4 on 2026-08-24 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_form_engine', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('scores', models.JSONField(blank=True, help_text='Calculated scores by category', null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='freedom_ls_form_engine.form')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Form progress records',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, default='')),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('form_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='freedom_ls_form_engine.formprogress')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom_ls_form_engine.formquestion')),
                ('selected_options', models.ManyToManyField(blank=True, to='freedom_ls_form_engine.questionoption')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'unique_together': {('form_progress', 'question')},
            },
        ),
    ]
