# Generated by Django 6.0.4 on 2026-08-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_form_engine', '0002_formprogress_questionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formprogress',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='freedom_ls_form_engine.form'),
        ),
    ]
