# Generated by Django 6.0.4 on 2026-09-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_form_engine', '0002_alter_form_strategy_alter_formquestion_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswerfile',
            name='scan_status',
        ),
    ]
