# Generated by Django 6.0.4 on 2026-09-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_form_engine', '0003_remove_questionanswerfile_scan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formprogress',
            name='furthest_page_reached',
            field=models.PositiveSmallIntegerField(default=0, help_text='The highest-numbered page this sitting has been shown'),
        ),
    ]
