# Generated by Django 6.0.4 on 2026-09-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_form_engine', '0004_formprogress_furthest_page_reached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('checkboxes', 'Checkboxes'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('number', 'Number'), ('file_upload', 'File upload'), ('date', 'Date'), ('time', 'Time'), ('email', 'Email'), ('url', 'URL'), ('phone', 'Phone'), ('dropdown', 'Dropdown')], max_length=20),
        ),
    ]
