# Generated by Django 6.0.4 on 2026-08-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_form_engine', '0004_rename_last_updated_time_questionanswer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='freedom_ls_form_engine.formquestion'),
        ),
    ]
