# Generated by Django 6.0.4 on 2026-08-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_form_engine', '0005_alter_questionanswer_question'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='form',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_form_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='questionanswer',
            constraint=models.UniqueConstraint(fields=('form_progress', 'question'), name='one_answer_per_question_per_form_progress'),
        ),
    ]
