# Generated by Django 6.0.4 on 2026-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_form_engine', '0005_alter_formquestion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='max',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='min',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
