# Generated by Django 6.0.4 on 2026-09-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_form_engine', '0006_formquestion_max_formquestion_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
