# Generated by Django 6.0.4 on 2026-08-25 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freedom_ls_content_engine', '0016_delete_form_delete_formcontent_delete_formpage_and_more'),
        ('freedom_ls_form_engine', '0003_alter_formprogress_form'),
        ('freedom_ls_learner_management', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(db_index=True, default=0)),
                ('cohort_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_progress_records', to='freedom_ls_learner_management.cohortcourseregistration')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='freedom_ls_content_engine.course')),
                ('last_accessed_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='freedom_ls_content_engine.contentcollectionitem')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_progress_records', to='freedom_ls_learner_management.learner')),
                ('learner_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_progress_records', to='freedom_ls_learner_management.learnercourseregistration')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'course progress record',
                'verbose_name_plural': 'course progress records',
            },
        ),
        migrations.CreateModel(
            name='CourseFormAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_attempts', to='freedom_ls_content_engine.contentcollectionitem')),
                ('form_progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_attempt', to='freedom_ls_form_engine.formprogress')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_attempts', to='freedom_ls_learner_progress.courseprogress')),
            ],
            options={
                'verbose_name': 'course form attempt',
                'verbose_name_plural': 'course form attempts',
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_time', models.DateTimeField(auto_now=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('collection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_progress', to='freedom_ls_content_engine.contentcollectionitem')),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='freedom_ls_learner_progress.courseprogress')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='freedom_ls_content_engine.topic')),
            ],
            options={
                'verbose_name': 'topic progress record',
                'verbose_name_plural': 'topic progress records',
            },
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['learner', 'course'], name='freedom_ls__learner_6961de_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.UniqueConstraint(fields=('learner_registration', 'learner'), name='one_course_progress_per_learner_registration'),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.UniqueConstraint(fields=('cohort_registration', 'learner'), name='one_course_progress_per_cohort_registration'),
        ),
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cohort_registration__isnull', True), ('learner_registration__isnull', False)), models.Q(('cohort_registration__isnull', False), ('learner_registration__isnull', True)), _connector='OR'), name='course_progress_has_exactly_one_grant'),
        ),
        migrations.AddIndex(
            model_name='courseformattempt',
            index=models.Index(fields=['course_progress', 'collection_item'], name='freedom_ls__course__f8194b_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['course_progress', 'complete_time'], name='freedom_ls__course__1f1f33_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicprogress',
            constraint=models.UniqueConstraint(fields=('course_progress', 'collection_item'), name='one_topic_progress_per_placement_per_record'),
        ),
    ]
