# Generated by Django 6.0.4 on 2026-08-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_form_engine', '0001_initial'),
        ('freedom_ls_learner_progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formprogress',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='freedom_ls_form_engine.form'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom_ls_form_engine.formquestion'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='freedom_ls_form_engine.questionoption'),
        ),
    ]
