# Generated by Django 6.0.4 on 2026-08-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_learner_progress', '0002_alter_formprogress_form_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='form_progress',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='selected_options',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='site',
        ),
        migrations.DeleteModel(
            name='FormProgress',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
