# Generated by Django 5.2.9 on 2026-03-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_student_progress', '0003_add_progress_percentage_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='text_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
