# Generated by Django 6.0.4 on 2026-06-01 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('freedom_ls_student_progress', '0004_alter_questionanswer_text_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='last_accessed_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='last_accessed_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
