# Generated by Django 6.0.4 on 2026-09-08 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTouchCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('advert_code', models.CharField(blank=True, max_length=64)),
                ('utm_source', models.CharField(blank=True, max_length=64)),
                ('utm_medium', models.CharField(blank=True, max_length=64)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=128)),
                ('utm_term', models.CharField(blank=True, max_length=128)),
                ('is_overflow', models.BooleanField(default=False)),
                ('key_hash', models.CharField(max_length=64)),
                ('count', models.PositiveIntegerField(default=0, help_text='Counts cookie mints, not visitors: bots and link unfurlers inflate it. Use it to compare campaigns against each other, not as an absolute count.')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'utm_source'], name='freedom_ls__site_id_a80410_idx'), models.Index(fields=['site', 'utm_campaign'], name='freedom_ls__site_id_76d038_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'day', 'key_hash'), name='unique_first_touch_count')],
            },
        ),
        migrations.CreateModel(
            name='SignupAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advert_code', models.CharField(blank=True, max_length=64)),
                ('utm_source', models.CharField(blank=True, max_length=64)),
                ('utm_medium', models.CharField(blank=True, max_length=64)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=128)),
                ('utm_term', models.CharField(blank=True, max_length=128)),
                ('gclid', models.CharField(blank=True, max_length=128)),
                ('gbraid', models.CharField(blank=True, max_length=128)),
                ('wbraid', models.CharField(blank=True, max_length=128)),
                ('fbclid', models.CharField(blank=True, max_length=256)),
                ('landing_path', models.CharField(blank=True, max_length=255)),
                ('referer', models.CharField(blank=True, max_length=255)),
                ('raw_query', models.CharField(blank=True, max_length=512)),
                ('first_seen', models.DateTimeField()),
                ('ga_cookie', models.CharField(blank=True, max_length=64)),
                ('fbp_cookie', models.CharField(blank=True, max_length=64)),
                ('fbc_cookie', models.CharField(blank=True, max_length=320)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_attribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_up_at'],
                'indexes': [models.Index(fields=['site', 'signed_up_at'], name='freedom_ls__site_id_2f5036_idx'), models.Index(fields=['site', 'utm_source'], name='freedom_ls__site_id_ea2ad5_idx'), models.Index(fields=['site', 'utm_campaign'], name='freedom_ls__site_id_2e4550_idx')],
            },
        ),
    ]
