# Generated by Django 6.0.4 on 2026-09-12 07:31

import django.db.models.deletion
import django.db.models.functions.text
import freedom_ls.referral_tracking.codes
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_referral_tracking', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsttouchcount',
            name='referral_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='signupattribution',
            name='referral_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Leave blank to generate an 8-character print code. The code cannot be changed once the referral code is saved.', max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.CharField(max_length=512, validators=[freedom_ls.referral_tracking.codes.validate_site_path])),
                ('inactive_destination', models.CharField(blank=True, max_length=512, validators=[freedom_ls.referral_tracking.codes.validate_site_path])),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='Counts hits not flagged as a machine fetch: an upper bound on human use, not a scan count. Link previews, mail scanners and crawlers that imitate a browser still inflate it. This number and the hit log do not reconcile — the log holds every hit, machine fetches included, and pruning empties it, while this count skips machine fetches and never goes down.')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCodeHit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('door', models.CharField(choices=[('go', '/go/'), ('d', '/d/')], max_length=2)),
                ('is_machine_fetch', models.BooleanField()),
                ('hit_at', models.DateTimeField(auto_now_add=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='freedom_ls_referral_tracking.referralcode')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
        migrations.AddConstraint(
            model_name='referralcode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('site'), name='unique_referral_code_per_site'),
        ),
        migrations.AddIndex(
            model_name='referralcodehit',
            index=models.Index(fields=['site', 'hit_at'], name='freedom_ls__site_id_0b8d40_idx'),
        ),
    ]
