# Generated by Django 6.0.4 on 2026-09-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_referral_tracking', '0002_firsttouchcount_referral_code_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='referralcodehit',
            index=models.Index(fields=['hit_at'], name='freedom_ls__hit_at_16a0f2_idx'),
        ),
    ]
