# Generated by Django 6.0.4 on 2026-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_referral_tracking', '0003_referralcodehit_freedom_ls__hit_at_16a0f2_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='hit_count',
            field=models.PositiveIntegerField(default=0, help_text='Counts hits not flagged as a machine fetch: an upper bound on human use, not a scan count. Link previews, mail scanners and crawlers that imitate a browser still inflate it. This number and the hit log do not reconcile — the log holds every hit, machine fetches included, and pruning empties it, while this count skips machine fetches and never goes down. Repeated hits from one address are capped per hour, so heavy use from a single connection is undercounted.'),
        ),
    ]
