# Generated by Django 6.0.4 on 2026-08-28 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0019_alter_activity_unique_together_and_more'),
        ('freedom_ls_course_interest', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseinterest',
            name='unique_course_interest',
        ),
        migrations.AddConstraint(
            model_name='courseinterest',
            constraint=models.UniqueConstraint(fields=('site', 'user', 'course'), name='unique_course_interest'),
        ),
    ]
