# Django 6 type stubs gap: remove these type: ignore comments when django-stubs
# releases Django 6 support. See spec_dd/2. in progress/01. upgrade-to-django-6/1. spec.md

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import base64
import hashlib
import os
import sys
from pathlib import Path

from django.utils.csp import (  # type: ignore[import-untyped]  # django-stubs lacks Django 6 support
    CSP,
)

from freedom_ls.accounts.email_utils import parse_tailwind_colors
from freedom_ls.base.webhook_event_types import FLS_WEBHOOK_EVENT_TYPES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, "concrete_apps"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    # "django.contrib.admin",
    "whitenoise.runserver_nostatic",
    "django_cotton.apps.SimpleAppConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.tasks",
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    "django.contrib.admin",  # required
    "guardian",
    "heroicons",
    # CUSTOM APPS
    # "app_authentication",
    # xapi_learning_record_store
    "freedom_ls.base",
    "freedom_ls.content_engine",
    "freedom_ls.accounts",
    "freedom_ls.student_management",
    "freedom_ls.student_progress",
    "freedom_ls.site_aware_models",
    "freedom_ls.educator_interface",
    "freedom_ls.role_based_permissions",
    #########
    # STUDENT INTERFACE
    "freedom_ls.student_interface",
    #########
    "django_premailer",
    # AllAuth is at the end because we need to override many of its templates
    "encrypted_fields",
    "freedom_ls.webhooks",
    "allauth",
    "allauth.account",
]

# These are the URLs to be implemented by your single-page application.
# HEADLESS_FRONTEND_URLS = {
#     "account_confirm_email": "https://app.project.org/account/verify-email/{key}",
#     "account_reset_password_from_key": "https://app.org/account/password/reset/key/{key}",
#     "account_signup": "https://app.org/account/signup",
# }
# TODO

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "freedom_ls.site_aware_models.middleware.CurrentSiteMiddleware",
    # "config.site_urlconf_middleware.SiteURLConfMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

X_FRAME_OPTIONS = "SAMEORIGIN"  # needed for pdf display

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # "DIRS": [],
        "DIRS": [
            # BASE_DIR / "templates",
            "/tmp/lms_templates"  # noqa: S108
        ],
        # "APP_DIRS": True,
        "OPTIONS": {
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django_cotton.cotton_loader.Loader",
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ],
                )
            ],
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "freedom_ls.site_aware_models.context_processors.site_config",
                "freedom_ls.accounts.context_processors.signup_policy",
                "django.template.context_processors.csp",
                "freedom_ls.accounts.context_processors.email_settings",
            ],
            "builtins": [
                "django_cotton.templatetags.cotton",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (User uploaded files)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "freedom_ls_accounts.User"


# UNFOLD = {
#     "SITE_TITLE": get_unfold_value("SITE_TITLE"),
#     "SITE_HEADER": get_unfold_value("SITE_HEADER"),
#     "SHOW_VIEW_ON_SITE": False,
#     "COLORS": get_unfold_value("COLORS"),
# }


AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)


MARKDOWN_ALLOWED_TAGS = {
    "c-youtube": {"video_id", "video_title"},
    "c-picture": {"src", "alt", "caption"},
    "c-callout": {"level", "title"},
    "c-content-link": {"path"},
    "c-pdf-embed": {"src", "caption", "height"},
    "c-file-download": {"src", "text"},
}

MARKDOWN_TEMPLATE_RENDER_ON = True
COTTON_SNAKE_CASED_NAMES = False


###
# ALLAUTH

# HEADLESS_CLIENTS = ("app",)
ACCOUNT_SIGNUP_FIELDS = ["email*", "email2*", "password1*", "password2*"]
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_ADAPTER = "freedom_ls.accounts.allauth_account_adapter.AccountAdapter"


# ACCOUNT_ADAPTER = "freedom_ls.accounts.allauth_account_adapter.AccountAdapter"
ALLOW_SIGN_UPS = True

# HEADLESS_FRONTEND_URLS = TODO

# HEADLESS_TOKEN_STRATEGY = default = allauth.headless.tokens.sessions.SessionTokenStrategy

# Email template settings
EMAIL_LOGO_STATIC_PATH = None  # e.g., "images/logo.png"
EMAIL_FONT_FAMILY = "Arial, Helvetica, sans-serif"
ACCOUNT_EMAIL_NOTIFICATIONS = True


_tw_colors = parse_tailwind_colors(str(BASE_DIR / "tailwind.components.css"))
EMAIL_COLOR_PRIMARY = _tw_colors.get("primary", "#2B6CB0")
EMAIL_COLOR_FOREGROUND = _tw_colors.get("foreground", "#1A2332")
EMAIL_COLOR_MUTED = _tw_colors.get("muted", "#4A5568")
EMAIL_COLOR_SURFACE = _tw_colors.get("surface", "#FFFFFF")
EMAIL_COLOR_SURFACE_2 = _tw_colors.get("surface-2", "#F3F4F6")
EMAIL_COLOR_ON_PRIMARY = _tw_colors.get("on-primary", "#FFFFFF")
EMAIL_COLOR_BORDER = _tw_colors.get("border", "#D1D5DB")

LOGIN_REDIRECT_URL = "/"

# Webhook event types
WEBHOOK_EVENT_TYPES = FLS_WEBHOOK_EVENT_TYPES


# Content Security Policy (report-only mode)
SECURE_CSP_REPORT_ONLY = {
    "default-src": [CSP.SELF],
    "script-src": [CSP.SELF, CSP.UNSAFE_INLINE],
    "style-src": [CSP.SELF, CSP.UNSAFE_INLINE],
    "img-src": [CSP.SELF, "data:"],
    "connect-src": [CSP.SELF],
    "frame-src": [
        CSP.SELF,
        "https://www.youtube.com",
        "https://www.youtube-nocookie.com",
    ],
}


# Background Tasks Framework
# Using ImmediateBackend for development. A production backend
# (e.g., database-backed) is needed before using tasks in production.
TASKS = {
    "default": {
        "BACKEND": "django.tasks.backends.immediate.ImmediateBackend",
    },
}

# Webhook encryption for django-fernet-encrypted-fields.
# The library derives Fernet keys from SECRET_KEY + SALT_KEY using PBKDF2.
# In production: set WEBHOOK_ENCRYPTION_SALT environment variable.
# In development: a deterministic salt is derived from SECRET_KEY.
#
# django-fernet-encrypted-fields supports MultiFernet key rotation via
# SECRET_KEY_FALLBACKS — provide old SECRET_KEYs there so existing encrypted
# data can still be decrypted. The current SECRET_KEY is always used for
# new encryption.
_webhook_salt = os.environ.get("WEBHOOK_ENCRYPTION_SALT", "")
if not _webhook_salt:
    # Development fallback: derive a deterministic salt from a hardcoded string.
    # This is NOT secure for production — always set the env var in production.
    _webhook_salt = base64.urlsafe_b64encode(
        hashlib.sha256(b"webhook-encryption-salt-dev").digest()
    ).decode()
SALT_KEY = _webhook_salt
