# Generated by Django 6.0.4 on 2026-08-28 18:44

import django.core.validators
import django.db.models.deletion
import freedom_ls.organisations.models
import freedom_ls.organisations.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150)),
                ('logo', models.ImageField(blank=True, help_text='The full-colour mark, for white and near-white surfaces. Used on the report cover and anywhere the organisation appears on screen.', storage=freedom_ls.organisations.models.get_organisation_logo_storage, upload_to=freedom_ls.organisations.models.organisation_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp']), freedom_ls.organisations.validators.validate_organisation_logo], verbose_name='logo (for light backgrounds)')),
                ('logo_on_dark', models.ImageField(blank=True, help_text="The reversed mark, for surfaces painted in a strong colour. Optional — a surface with no dark variant to reach for falls back to the organisation's name.", storage=freedom_ls.organisations.models.get_organisation_logo_storage, upload_to=freedom_ls.organisations.models.organisation_logo_on_dark_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp']), freedom_ls.organisations.validators.validate_organisation_logo], verbose_name='logo (for dark backgrounds)')),
                ('is_default', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_organisation_slug_per_site'), models.UniqueConstraint(fields=('site', 'name'), name='unique_organisation_name_per_site'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('site',), name='one_default_organisation_per_site')],
            },
        ),
    ]
