# Generated by Django 6.0.4 on 2026-08-11 09:56

import django.core.validators
import django.db.models.deletion
import freedom_ls.organisations.models
import freedom_ls.organisations.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(max_length=150)),
                ('logo', models.ImageField(blank=True, upload_to=freedom_ls.organisations.models.organisation_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp']), freedom_ls.organisations.validators.validate_organisation_logo])),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_organisation_slug_per_site'), models.UniqueConstraint(fields=('site', 'name'), name='unique_organisation_name_per_site')],
            },
        ),
    ]
