# Generated by Django 6.0.4 on 2026-08-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_organisations', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('site',), name='one_default_organisation_per_site'),
        ),
    ]
