# Generated by Django 6.0.4 on 2026-08-26 04:19

import django.core.validators
import freedom_ls.organisations.models
import freedom_ls.organisations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_organisations', '0002_organisation_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, storage=freedom_ls.organisations.models.get_organisation_logo_storage, upload_to=freedom_ls.organisations.models.organisation_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp']), freedom_ls.organisations.validators.validate_organisation_logo]),
        ),
    ]
