# Generated by Django 6.0.4 on 2026-08-27 17:18

import django.core.validators
import freedom_ls.organisations.models
import freedom_ls.organisations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_organisations', '0003_alter_organisation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo_on_dark',
            field=models.ImageField(blank=True, help_text="The reversed mark, for surfaces painted in a strong colour. Optional — a surface with no dark variant to reach for falls back to the organisation's name.", storage=freedom_ls.organisations.models.get_organisation_logo_storage, upload_to=freedom_ls.organisations.models.organisation_logo_on_dark_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp']), freedom_ls.organisations.validators.validate_organisation_logo], verbose_name='logo (for dark backgrounds)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, help_text='The full-colour mark, for white and near-white surfaces. Used on the report cover and anywhere the organisation appears on screen.', storage=freedom_ls.organisations.models.get_organisation_logo_storage, upload_to=freedom_ls.organisations.models.organisation_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp']), freedom_ls.organisations.validators.validate_organisation_logo], verbose_name='logo (for light backgrounds)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=150),
        ),
    ]
