# Generated by Django 6.0.4 on 2026-08-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_organisations', '0003_organisation_logo_on_dark_alter_organisation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=150),
        ),
    ]
