# Generated by Django 6.0.4 on 2026-09-08 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_course_applications', '0001_initial'),
        ('freedom_ls_form_engine', '0002_alter_form_strategy_alter_formquestion_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='freedom_ls_form_engine.form'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='form_progress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_application', to='freedom_ls_form_engine.formprogress'),
        ),
    ]
