# Generated by Django 6.0.4 on 2026-09-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_course_applications', '0002_courseapplication_form_and_more'),
        ('freedom_ls_form_engine', '0002_alter_form_strategy_alter_formquestion_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseapplication',
            name='form',
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='form_progress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='course_application', to='freedom_ls_form_engine.formprogress'),
        ),
    ]
