# Generated by Django 6.0.4 on 2026-10-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_course_applications', '0005_backfill_application_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
