# Generated by Django 6.0.4 on 2026-04-24 15:06

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorErasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_user_id', models.BigIntegerField()),
                ('erased_token', models.CharField(max_length=64)),
                ('event_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoking_os_user', models.CharField(max_length=256)),
                ('invoking_hostname', models.CharField(max_length=256)),
                ('invoking_admin_user_id', models.BigIntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'indexes': [models.Index(fields=['target_user_id'], name='expapi_erase_user_idx'), models.Index(fields=['-timestamp'], name='expapi_erase_ts_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_domain', models.CharField(max_length=253)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('actor_display_name', models.CharField(blank=True, default='', max_length=512)),
                ('actor_ifi', models.CharField(blank=True, default='', max_length=512)),
                ('verb', models.CharField(max_length=512)),
                ('verb_display', models.CharField(max_length=64)),
                ('object_type', models.CharField(max_length=128)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('object_definition', models.JSONField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('context', models.JSONField(default=dict)),
                ('statement', models.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('stored', models.DateTimeField(auto_now_add=True)),
                ('session_id_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1024, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('platform', models.CharField(default='backend', max_length=32)),
                ('actor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'verb', '-timestamp'], name='expapi_event_site_verb_ts'), models.Index(fields=['site', 'actor_user', '-timestamp'], name='expapi_event_site_actor_ts'), models.Index(fields=['site', 'object_type', 'object_id', '-timestamp'], name='expapi_event_site_obj_ts'), django.contrib.postgres.indexes.BrinIndex(fields=['timestamp'], name='expapi_event_ts_brin'), django.contrib.postgres.indexes.GinIndex(fields=['context'], name='expapi_event_ctx_gin', opclasses=['jsonb_path_ops']), django.contrib.postgres.indexes.GinIndex(fields=['result'], name='expapi_event_result_gin', opclasses=['jsonb_path_ops'])],
            },
        ),
    ]
