# Generated by Django 6.0.4 on 2026-04-24 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_api', '0003_erasure_role_read_insert'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['site', 'actor_ifi'], name='expapi_event_site_ifi'),
        ),
    ]
