#!/bin/bash
# db_clear.sh — Generated by the django-stack (ds) plugin init
# Customize the "Project-specific setup" section below.

# PLUGINS_ROOT is set during `ds:init` to the relative path from the project root
# to the checkout that holds `claude_plugins/` (default "." — the project root itself).
PLUGINS_ROOT="."
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
PLUGIN_DIR="$PROJECT_ROOT/$PLUGINS_ROOT/claude_plugins/django-stack"

# === Base setup ===
"$PLUGIN_DIR/scripts/db_clear.sh" "$@"

# === Project-specific setup ===
# Add your implementation-specific steps below:
