#!/bin/bash
# rebase_lost_change_check.sh — Generated by the django-stack (ds) plugin init
# Only locates the plugin script. Its exit code is the check's result, so the script is
# exec'd and nothing below the base setup runs. Do not add project steps here.

# PLUGINS_ROOT is set during `ds:init` to the relative path from the project root
# to the checkout that holds `claude_plugins/` (default "." — the project root itself).
PLUGINS_ROOT="."
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
PLUGIN_DIR="$PROJECT_ROOT/$PLUGINS_ROOT/claude_plugins/django-stack"

# === Base setup ===
exec "$PLUGIN_DIR/scripts/rebase_lost_change_check.sh" "$@"

# === Project-specific setup ===
# Add your implementation-specific steps below:
