#!/bin/bash
# select_tests.sh — Generated by the django-stack (ds) plugin init
# Only locates the plugin script. Its output and exit code are the selection's result, so the
# script is exec'd and nothing below the base setup runs. Do not add project steps here.

# PLUGINS_ROOT is set during `ds:init` to the relative path from the project root
# to the checkout that holds `claude_plugins/` (default "." — the project root itself).
PLUGINS_ROOT="."
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
PLUGIN_DIR="$PROJECT_ROOT/$PLUGINS_ROOT/claude_plugins/django-stack"

# === Base setup ===
# git prints diff paths relative to the repository root and untracked paths relative to the
# current directory, and the script reads pyproject.toml and the app map from there too.
cd "$PROJECT_ROOT" || exit 1
exec uv run python "$PLUGIN_DIR/scripts/select_tests.py" "$@"

# === Project-specific setup ===
# Add your implementation-specific steps below:
