# Generated by Django 5.2.9 on 2026-03-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_accounts', '0002_sitesignuppolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
