# Generated by Django 5.2.9 on 2026-01-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_accounts', '0003_sitegroup_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitegroup',
            name='group_name',
            field=models.CharField(max_length=200),
        ),
    ]
