# Generated by Django 6.0.4 on 2026-04-27 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_accounts', '0003_alter_user_first_name_alter_user_last_name'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesignuppolicy',
            name='additional_registration_forms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesignuppolicy',
            name='require_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesignuppolicy',
            name='require_terms_acceptance',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LegalConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('terms', 'Terms'), ('privacy', 'Privacy')], max_length=16)),
                ('document_version', models.CharField(max_length=64)),
                ('git_hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_method', models.CharField(choices=[('signup_checkbox', 'Signup checkbox')], default='signup_checkbox', max_length=32)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'document_type'], name='freedom_ls__user_id_017c79_idx')],
            },
        ),
    ]
