# Generated by Django 6.0.4 on 2026-04-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_accounts', '0004_sitesignuppolicy_additional_registration_forms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalconsent',
            options={'ordering': ['-timestamp']},
        ),
    ]
