# Generated by Django 5.2.9 on 2026-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_student_progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
