# Generated by Django 5.2.9 on 2026-02-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_student_progress', '0002_courseprogress_progress_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='progress_percentage',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
