# Generated by Django 5.2.7 on 2025-11-01 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('TOPIC', 'Topic'), ('FORM', 'Form'), ('COLLECTION', 'Collection'), ('FORM_PAGE', 'Form Page'), ('FORM_QUESTION', 'Form Question'), ('FORM_TEXT', 'Form Text')], db_index=True, max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('children', models.JSONField(help_text='Single directory path or list of content paths')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('TOPIC', 'Topic'), ('FORM', 'Form'), ('COLLECTION', 'Collection'), ('FORM_PAGE', 'Form Page'), ('FORM_QUESTION', 'Form Question'), ('FORM_TEXT', 'Form Text')], db_index=True, max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('strategy', models.CharField(choices=[('CATEGORY_VALUE_SUM', 'Category Value Sum')], max_length=50)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('TOPIC', 'Topic'), ('FORM', 'Form'), ('COLLECTION', 'Collection'), ('FORM_PAGE', 'Form Page'), ('FORM_QUESTION', 'Form Question'), ('FORM_TEXT', 'Form Text')], db_index=True, max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='content_engine.form')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('TOPIC', 'Topic'), ('FORM', 'Form'), ('COLLECTION', 'Collection'), ('FORM_PAGE', 'Form Page'), ('FORM_QUESTION', 'Form Question'), ('FORM_TEXT', 'Form Text')], db_index=True, max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('checkboxes', 'Checkboxes'), ('short_text', 'Short Text'), ('long_text', 'Long Text')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content_engine.formpage')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('TOPIC', 'Topic'), ('FORM', 'Form'), ('COLLECTION', 'Collection'), ('FORM_PAGE', 'Form Page'), ('FORM_QUESTION', 'Form Question'), ('FORM_TEXT', 'Form Text')], db_index=True, max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('form_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_items', to='content_engine.formpage')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content_engine.formquestion')),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('TOPIC', 'Topic'), ('FORM', 'Form'), ('COLLECTION', 'Collection'), ('FORM_PAGE', 'Form Page'), ('FORM_QUESTION', 'Form Question'), ('FORM_TEXT', 'Form Text')], db_index=True, max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
