# Generated by Django 5.2.7 on 2025-11-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
