# Generated by Django 5.2.7 on 2025-11-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcollection',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='form',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='formtext',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='file_path',
        ),
    ]
