# Generated by Django 5.2.7 on 2025-11-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0002_remove_contentcollection_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcollection',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='form',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='formtext',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content_type',
        ),
    ]
