# Generated by Django 5.2.7 on 2025-11-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0003_remove_contentcollection_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown content', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown content', null=True),
        ),
    ]
