# Generated by Django 5.2.7 on 2025-11-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0004_form_content_topic_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentCollection',
        ),
    ]
