# Generated by Django 5.2.7 on 2025-11-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0005_delete_contentcollection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='formpage',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='formquestion',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='formtext',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='questionoption',
            old_name='site_id',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='site_id',
            new_name='site',
        ),
    ]
