# Generated by Django 5.2.7 on 2025-11-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0007_contentcollection_contentcollectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcollection',
            name='file_path',
            field=models.CharField(default='', help_text='Relative path to the source file', max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='file_path',
            field=models.CharField(default='', help_text='Relative path to the source file', max_length=500),
        ),
        migrations.AddField(
            model_name='formpage',
            name='file_path',
            field=models.CharField(default='', help_text='Relative path to the source file', max_length=500),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='file_path',
            field=models.CharField(default='', help_text='Relative path to the source file', max_length=500),
        ),
        migrations.AddField(
            model_name='formtext',
            name='file_path',
            field=models.CharField(default='', help_text='Relative path to the source file', max_length=500),
        ),
        migrations.AddField(
            model_name='topic',
            name='file_path',
            field=models.CharField(default='', help_text='Relative path to the source file', max_length=500),
        ),
    ]
