# Generated by Django 5.2.7 on 2025-11-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0008_contentcollection_file_path_form_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcollection',
            name='file_path',
            field=models.CharField(help_text='Relative path to the source file', max_length=500),
        ),
        migrations.AlterField(
            model_name='form',
            name='file_path',
            field=models.CharField(help_text='Relative path to the source file', max_length=500),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='file_path',
            field=models.CharField(help_text='Relative path to the source file', max_length=500),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='file_path',
            field=models.CharField(help_text='Relative path to the source file', max_length=500),
        ),
        migrations.AlterField(
            model_name='formtext',
            name='file_path',
            field=models.CharField(help_text='Relative path to the source file', max_length=500),
        ),
        migrations.AlterField(
            model_name='topic',
            name='file_path',
            field=models.CharField(help_text='Relative path to the source file', max_length=500),
        ),
    ]
