# Generated by Django 5.2.7 on 2025-11-05 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0009_alter_contentcollection_file_path_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('form_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_items', to='content_engine.formpage')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='FormText',
        ),
    ]
