# Generated by Django 5.2.7 on 2025-11-05 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0010_formcontent_delete_formtext'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='gitignore/content_files/%Y/%m/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'unique_together': {('site', 'file_path')},
            },
        ),
    ]
