"""Generate ``tailwind.active_theme.css`` at the project root.

Writes a single ``@import`` pointing at the active theme's ``theme.css``,
resolved through Django settings (``FLS_THEME`` + ``FLS_THEMES_DIRS``) so the
Tailwind build and the Django runtime cannot disagree about which file is the
active theme. Invoked by the ``tailwind_build`` / ``tailwind_watch`` npm
scripts immediately before Tailwind compiles ``tailwind.input.css``.

Cascade contract (Phase 2 of themable-implementations):

    - ``tailwind.input.css`` imports the default theme as the always-on
      baseline.
    - It then imports ``tailwind.components.css``.
    - It then imports the generated ``tailwind.active_theme.css`` so the
      active theme's tokens win on cascade. When ``FLS_THEME=default``, this
      import is a re-import of the same file (a no-op against the baseline).

The generated file is intentionally gitignored.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError


class Command(BaseCommand):
    help = "Write tailwind.active_theme.css for the active FLS theme."

    def handle(self, *args: Any, **options: Any) -> None:
        base_dir: Path = settings.BASE_DIR
        slug: str = settings.FLS_THEME
        resolved_dir: Path = settings.RESOLVED_THEME_DIR

        theme_css = resolved_dir / "static" / "themes" / slug / "theme.css"
        if not theme_css.is_file():
            raise CommandError(
                f"FLS_THEME={slug!r} resolves to {resolved_dir}, but "
                f"{theme_css} does not exist. Add the file or fix the slug."
            )

        # Tailwind reads the generated file from BASE_DIR, so prefer a
        # BASE_DIR-relative @import. Themes that live outside BASE_DIR (a
        # downstream project pointing FLS_THEMES_DIRS at e.g. a sibling
        # checkout) fall back to an absolute path.
        try:
            import_path = "./" + theme_css.relative_to(base_dir).as_posix()
        except ValueError:
            import_path = theme_css.as_posix()
        contents = (
            "/* Generated by manage.py write_active_theme_css "
            "— do not edit by hand. */\n"
            f'@import "{import_path}";\n'
        )
        (base_dir / "tailwind.active_theme.css").write_text(contents)
