# Generated by Django 6.0.4 on 2026-08-28 18:44

import django.contrib.postgres.fields
import django.db.models.deletion
import freedom_ls.content_engine.models.files
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Optional list of tags')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=500)),
                ('content', models.TextField(blank=True, default='', help_text='Markdown content')),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_activity_slug_per_site')],
            },
        ),
        migrations.CreateModel(
            name='ContentCollectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_id', models.UUIDField()),
                ('child_id', models.UUIDField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('overrides', models.JSONField(blank=True, help_text='Optional overrides as key-value pairs', null=True)),
                ('child_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_items', to='contenttypes.contenttype')),
                ('collection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['collection_type', 'collection_id'], name='cci_collection_idx'), models.Index(fields=['child_type', 'child_id'], name='cci_child_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Optional list of tags')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=500)),
                ('content', models.TextField(blank=True, default='', help_text='Markdown content')),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('access_config', models.JSONField(blank=True, default=dict, help_text="Opaque per-course access configuration. Interpreted ONLY by the active course-access backend (settings.COURSE_ACCESS_BACKEND); core never reads or branches on its contents. The default backend stores {'access_type': ...}.")),
                ('icon', models.CharField(blank=True, default='', help_text="Semantic icon name (e.g. 'notes') or a literal glyph name (e.g. 'drone'). Empty means render the default 'course' icon.", max_length=64)),
                ('icon_fallback', models.CharField(blank=True, default='', help_text="Optional '<iconset>:<glyph>' reference, used only when 'icon' is a literal glyph that does not resolve in the active icon set.", max_length=80)),
                ('accent_slot', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('learning_outcomes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Ordered list of 'what you'll learn' outcomes. Empty hides the section.")),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All levels')], default='', max_length=20)),
                ('visibility', models.CharField(choices=[('published', 'Published'), ('coming_soon', 'Coming soon'), ('hidden', 'Hidden')], db_index=True, default='published', max_length=20)),
                ('table_of_contents_in_development', models.BooleanField(default=False)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_course_slug_per_site')],
            },
        ),
        migrations.CreateModel(
            name='CoursePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Optional list of tags')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_course_part_slug_per_site')],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=freedom_ls.content_engine.models.files.get_content_media_storage, upload_to=freedom_ls.content_engine.models.files.file_upload_handler)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'file_path'), name='unique_file_path_per_site')],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Optional list of tags')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=500)),
                ('content', models.TextField(blank=True, default='', help_text='Markdown content')),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_topic_slug_per_site')],
            },
        ),
    ]
