# Generated by Django 6.0.4 on 2026-09-08 17:11

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title', 'pk']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Optional list of tags')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_on_dashboard', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='courses', to='freedom_ls_content_engine.coursecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='dashboard_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_courses', to='freedom_ls_content_engine.coursecategory'),
        ),
        migrations.AddConstraint(
            model_name='coursecategory',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_course_category_slug_per_site'),
        ),
    ]
