# Generated by Django 6.0.4 on 2026-09-08 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0001_initial'),
        ('freedom_ls_form_engine', '0002_alter_form_strategy_alter_formquestion_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='application_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_courses', to='freedom_ls_form_engine.form'),
        ),
    ]
