# Generated by Django 5.2.9 on 2026-02-02 09:07

import freedom_ls.content_engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=freedom_ls.content_engine.models.file_upload_handler),
        ),
    ]
