# Generated by Django 5.2.8 on 2025-12-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0002_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
