# Generated by Django 5.2.9 on 2026-02-09 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_collection_to_generic_fk(apps, schema_editor):
    """Migrate data from collection_old FK to collection_type/collection_id GenericFK."""
    ContentCollectionItem = apps.get_model('freedom_ls_content_engine', 'ContentCollectionItem')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Course = apps.get_model('freedom_ls_content_engine', 'Course')

    # Get the ContentType for Course
    course_content_type = ContentType.objects.get_for_model(Course)

    # Update all ContentCollectionItem records
    for item in ContentCollectionItem.objects.all():
        if item.collection_old_id:
            item.collection_type = course_content_type
            item.collection_id = item.collection_old_id
            item.save(update_fields=['collection_type', 'collection_id'])


def reverse_migration(apps, schema_editor):
    """Reverse the migration by copying back to collection_old."""
    ContentCollectionItem = apps.get_model('freedom_ls_content_engine', 'ContentCollectionItem')

    # Copy data back from collection_id to collection_old_id
    for item in ContentCollectionItem.objects.all():
        if item.collection_id:
            item.collection_old_id = item.collection_id
            item.save(update_fields=['collection_old_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('freedom_ls_content_engine', '0002_alter_file_file'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentcollectionitem',
            old_name='collection',
            new_name='collection_old',
        ),
        migrations.AlterUniqueTogether(
            name='contentcollectionitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contentcollectionitem',
            name='collection_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentcollectionitem',
            name='collection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='contentcollectionitem',
            name='child_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_items', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='CoursePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=500)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'unique_together': {('site', 'slug')},
            },
        ),
        # Migrate the data from collection_old to collection_type/collection_id
        migrations.RunPython(migrate_collection_to_generic_fk, reverse_migration),
    ]
