# Generated by Django 6.0.4 on 2026-09-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0002_alter_course_options_remove_course_category_and_more'),
        ('freedom_ls_content_engine', '0002_course_application_form'),
    ]

    operations = [
    ]
