# Generated by Django 5.2.8 on 2025-12-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0003_activity_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='form',
            name='quiz_show_incorrect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
