# Generated by Django 6.0.4 on 2026-09-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0003_merge_20260910_0459'),
        ('freedom_ls_form_engine', '0007_formquestion_decimal_places'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='price_high_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price_kind',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('range', 'Range'), ('discounted', 'Discounted'), ('on_request', 'On request')], default='', help_text='Empty means the course has no price.', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='price_low_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price_sale_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price_sale_ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price_tax_note',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price_kind', ''), ('price_amount__isnull', True), ('price_high_amount__isnull', True), ('price_low_amount__isnull', True), ('price_sale_amount__isnull', True), ('price_sale_ends_on__isnull', True), ('price_currency', ''), ('price_tax_note', '')), models.Q(('price_kind', 'on_request'), ('price_amount__isnull', True), ('price_high_amount__isnull', True), ('price_low_amount__isnull', True), ('price_sale_amount__isnull', True), ('price_sale_ends_on__isnull', True), ('price_currency', ''), ('price_tax_note', '')), models.Q(('price_kind', 'fixed'), ('price_amount__gt', 0), ('price_high_amount__isnull', True), ('price_low_amount__isnull', True), ('price_sale_amount__isnull', True), ('price_sale_ends_on__isnull', True), models.Q(('price_currency', ''), _negated=True)), models.Q(('price_kind', 'range'), ('price_high_amount__gt', 0), ('price_low_amount__gt', 0), ('price_low_amount__lt', models.F('price_high_amount')), ('price_amount__isnull', True), ('price_sale_amount__isnull', True), ('price_sale_ends_on__isnull', True), models.Q(('price_currency', ''), _negated=True)), models.Q(('price_kind', 'discounted'), ('price_amount__gt', 0), ('price_sale_amount__gt', 0), ('price_sale_amount__lt', models.F('price_amount')), ('price_high_amount__isnull', True), ('price_low_amount__isnull', True), models.Q(('price_currency', ''), _negated=True)), _connector='OR'), name='course_price_fields_match_kind'),
        ),
    ]
