# Generated by Django 5.2.9 on 2026-02-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0003_rename_collection_contentcollectionitem_collection_old_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcollectionitem',
            name='collection_old',
        ),
    ]
