# Generated by Django 5.2.9 on 2026-02-15 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('freedom_ls_content_engine', '0004_remove_contentcollectionitem_collection_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcollectionitem',
            name='collection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contenttypes.contenttype'),
        ),
    ]
