# Generated by Django 6.0.4 on 2026-09-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0004_course_price_amount_course_price_currency_and_more'),
        ('freedom_ls_form_engine', '0007_formquestion_decimal_places'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='course_price_fields_match_kind',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price_kind', ''), ('price_amount__isnull', True), ('price_high_amount__isnull', True), ('price_low_amount__isnull', True), ('price_sale_amount__isnull', True), ('price_sale_ends_on__isnull', True), ('price_currency', ''), ('price_tax_note', '')), models.Q(('price_kind', 'on_request'), ('price_amount__isnull', True), ('price_high_amount__isnull', True), ('price_low_amount__isnull', True), ('price_sale_amount__isnull', True), ('price_sale_ends_on__isnull', True), ('price_currency', ''), ('price_tax_note', '')), models.Q(('price_kind', 'fixed'), ('price_amount__gt', 0), ('price_amount__isnull', False), ('price_high_amount__isnull', True), ('price_low_amount__isnull', True), ('price_sale_amount__isnull', True), ('price_sale_ends_on__isnull', True), models.Q(('price_currency', ''), _negated=True)), models.Q(('price_kind', 'range'), ('price_low_amount__gt', 0), ('price_low_amount__isnull', False), models.Q(('price_high_amount__isnull', True), models.Q(('price_high_amount__gt', 0), ('price_low_amount__lt', models.F('price_high_amount'))), _connector='OR'), ('price_amount__isnull', True), ('price_sale_amount__isnull', True), ('price_sale_ends_on__isnull', True), models.Q(('price_currency', ''), _negated=True)), models.Q(('price_kind', 'discounted'), ('price_amount__isnull', False), ('price_sale_amount__isnull', False), ('price_amount__gt', 0), ('price_sale_amount__gt', 0), ('price_sale_amount__lt', models.F('price_amount')), ('price_high_amount__isnull', True), ('price_low_amount__isnull', True), models.Q(('price_currency', ''), _negated=True)), _connector='OR'), name='course_price_fields_match_kind'),
        ),
    ]
