# Generated by Django 5.2.9 on 2026-03-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0005_alter_contentcollectionitem_collection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Markdown content'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Markdown content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='coursepart',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='coursepart',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description'),
        ),
        migrations.AlterField(
            model_name='coursepart',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='form',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Markdown content'),
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description'),
        ),
        migrations.AlterField(
            model_name='form',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Markdown content'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
