# Generated by Django 6.0.4 on 2026-10-01 10:38

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0005_course_price_open_ended_range'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Optional list of tags')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=500)),
                ('content', models.TextField(blank=True, default='', help_text='Markdown content')),
                ('published_on', models.DateField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('visibility', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden')], db_index=True, default='published', max_length=20)),
                ('show_date', models.BooleanField(null=True)),
                ('show_author', models.BooleanField(null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'ordering': ['-published_on', 'slug'],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_article_slug_per_site')],
            },
        ),
    ]
