# Generated by Django 5.2.8 on 2025-12-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0005_remove_formquestion_correct_questionoption_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='quiz_pass_percentage',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Percentage (0-100) required to pass the quiz', null=True),
        ),
    ]
