# Generated by Django 6.0.4 on 2026-10-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, help_text='Image path, relative to the article file', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='image_alt',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
