# Generated by Django 6.0.4 on 2026-05-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0006_alter_activity_category_alter_activity_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(blank=True, default='', help_text="Semantic icon name (e.g. 'notes') or a literal glyph name (e.g. 'drone'). Empty means render the default 'course' icon.", max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='icon_fallback',
            field=models.CharField(blank=True, default='', help_text="Optional '<iconset>:<glyph>' reference, used only when 'icon' is a literal glyph that does not resolve in the active icon set.", max_length=80),
        ),
    ]
