# Generated by Django 6.0.4 on 2026-05-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0007_course_icon_course_icon_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='accent_slot',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
