# Generated by Django 6.0.4 on 2026-05-30 08:27

from django.db import migrations

from freedom_ls.content_engine.course_accent import PALETTE


def backfill_accent_slot(apps, schema_editor):
    """Assign slots in slug order per site so the distribution starts balanced."""
    Course = apps.get_model("freedom_ls_content_engine", "Course")
    site_ids = Course.objects.values_list("site_id", flat=True).distinct()
    for site_id in site_ids:
        courses = Course.objects.filter(site_id=site_id).order_by("slug")
        for index, course in enumerate(courses):
            course.accent_slot = index % len(PALETTE)
            course.save(update_fields=["accent_slot"])


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0008_course_accent_slot'),
    ]

    operations = [
        migrations.RunPython(backfill_accent_slot, reverse_code=migrations.RunPython.noop),
    ]
