# Generated by Django 6.0.4 on 2026-06-01 22:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0009_backfill_course_accent_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All levels')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Ordered list of 'what you'll learn' outcomes. Empty hides the section."),
        ),
    ]
