# Generated by Django 6.0.4 on 2026-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0009_backfill_course_accent_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='submit_on_exit',
            field=models.BooleanField(default=False, help_text='If True, leaving the test mid-attempt finalises and scores it. If False (default), the attempt is saved and can be resumed.'),
        ),
    ]
