# Generated by Django 6.0.4 on 2026-06-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0010_course_difficulty_course_estimated_duration_and_more'),
        ('freedom_ls_content_engine', '0010_form_submit_on_exit'),
    ]

    operations = [
    ]
