# Generated by Django 6.0.4 on 2026-06-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0011_merge_20260604_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_config',
            field=models.JSONField(blank=True, default=dict, help_text="Opaque per-course access configuration. Interpreted ONLY by the active course-access backend (settings.COURSE_ACCESS_BACKEND); core never reads or branches on its contents. The default backend stores {'access_type': ...}."),
        ),
    ]
