# Generated by Django 6.0.4 on 2026-06-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0012_course_access_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visibility',
            field=models.CharField(choices=[('published', 'Published'), ('coming_soon', 'Coming soon'), ('hidden', 'Hidden')], db_index=True, default='published', max_length=20),
        ),
    ]
