# Generated by Django 6.0.4 on 2026-07-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0013_course_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='table_of_contents_in_development',
            field=models.BooleanField(default=False),
        ),
    ]
