# Generated by Django 6.0.4 on 2026-08-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0014_course_table_of_contents_in_development'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='form',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='form',
            name='site',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formcontent',
            name='form_page',
        ),
        migrations.RemoveField(
            model_name='formcontent',
            name='site',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='site',
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='form_page',
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='site',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='site',
        ),
    ]
