# Generated by Django 6.0.4 on 2026-08-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0015_alter_form_unique_together_remove_form_site_and_more'),
        ('freedom_ls_learner_progress', '0002_alter_formprogress_form_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='FormContent',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
        migrations.DeleteModel(
            name='FormQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
