# Generated by Django 6.0.4 on 2026-08-26 04:19

import freedom_ls.content_engine.models.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0016_delete_form_delete_formcontent_delete_formpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=freedom_ls.content_engine.models.files.get_content_media_storage, upload_to=freedom_ls.content_engine.models.files.file_upload_handler),
        ),
    ]
