# Generated by Django 6.0.4 on 2026-08-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('freedom_ls_content_engine', '0018_activity_created_at_activity_updated_at_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='coursepart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='contentcollectionitem',
            index=models.Index(fields=['collection_type', 'collection_id'], name='cci_collection_idx'),
        ),
        migrations.AddIndex(
            model_name='contentcollectionitem',
            index=models.Index(fields=['child_type', 'child_id'], name='cci_child_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_activity_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_course_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='coursepart',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_course_part_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('site', 'file_path'), name='unique_file_path_per_site'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_topic_slug_per_site'),
        ),
    ]
