# Generated by Django 6.0.4 on 2026-08-28 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0019_alter_activity_unique_together_and_more'),
    ]

    # Hand-swapped from AlterField to RemoveField + AddField: Postgres has no implicit
    # cast from jsonb to text[], so the autogenerated AlterField fails even against an
    # empty table. Safe only because nothing populates tags yet.
    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='tags',
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Optional list of tags'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Optional list of tags'),
        ),
        migrations.RemoveField(
            model_name='coursepart',
            name='tags',
        ),
        migrations.AddField(
            model_name='coursepart',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Optional list of tags'),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tags',
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Optional list of tags'),
        ),
    ]
