#!/bin/bash
# qa_collect_screenshots.sh — Generated by fls plugin init
# Customize the "Project-specific setup" section below.

# FLS_PATH is set during `fls:init` to the path where FLS is installed
# (e.g., "submodules/Freedom-LS" for concrete implementations, or "." for FLS itself)
FLS_PATH="."
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
PLUGIN_DIR="$PROJECT_ROOT/$FLS_PATH/fls-claude-plugin"

# CLAUDE_PROJECT_DIR is not reliably exported into the Bash tool environment, but
# the canonical script requires it. Derive it from this wrapper's known location
# (the project root is three levels up from .claude/fls/scripts/) when unset.
: "${CLAUDE_PROJECT_DIR:=$(readlink -f "$PROJECT_ROOT")}"
export CLAUDE_PROJECT_DIR

# === FLS base setup ===
"$PLUGIN_DIR/scripts/qa_collect_screenshots.sh" "$@"

# === Project-specific setup ===
# Add your implementation-specific steps below:
