#!/usr/bin/env bash
# claude.sh — Generated by the django-stack (ds) plugin init
# Launches Claude Code with the dev plugins loaded (django-stack, fls-dev, sdd).

FLS_PATH="__FLS_PATH__"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CLAUDE_PLUGINS_LOADED=1 claude \
  --plugin-dir "$SCRIPT_DIR/$FLS_PATH/claude_plugins/django-stack-claude-plugin" \
  --plugin-dir "$SCRIPT_DIR/$FLS_PATH/claude_plugins/fls-dev-claude-plugin" \
  --plugin-dir "$SCRIPT_DIR/$FLS_PATH/claude_plugins/sdd-claude-plugin" \
  "$@"
