#!/bin/bash
# db_clear.sh — Generated by the django-stack (ds) plugin init
# Customize the "Project-specific setup" section below.

# FLS_PATH is set during `ds:init` to the path where FLS is installed
# (e.g., "submodules/Freedom-LS" for concrete implementations, or "." for FLS itself)
FLS_PATH="__FLS_PATH__"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
PLUGIN_DIR="$PROJECT_ROOT/$FLS_PATH/claude_plugins/django-stack-claude-plugin"

# === Base setup ===
"$PLUGIN_DIR/scripts/db_clear.sh" "$@"

# === Project-specific setup ===
# Add your implementation-specific steps below:
