#!/bin/bash
# kill_runserver.sh — Generated by the django-stack (ds) plugin init
# Customize the "Project-specific setup" section below.

# PLUGINS_ROOT is set during `ds:init` to the relative path from the project root
# to the checkout that holds `claude_plugins/` (default "." — the project root itself).
PLUGINS_ROOT="__PLUGINS_ROOT__"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
PLUGIN_DIR="$PROJECT_ROOT/$PLUGINS_ROOT/claude_plugins/django-stack-claude-plugin"

# === Base setup ===
"$PLUGIN_DIR/scripts/kill_runserver.sh" "$@"

# === Project-specific setup ===
# Add your implementation-specific steps below:
