SEMANTIC_ICON_NAMES: set[str] = {
    # Navigation
    "next",
    "previous",
    "home",
    "expand",
    "collapse",
    "menu_open",
    "menu_close",
    "table_of_contents",
    "dropdown",
    "fullscreen",
    "quick_view",
    "open_page",
    # Status
    "success",
    "error",
    "warning",
    "info",
    "in_progress",
    "complete",
    "locked",
    "rate_limit",
    "maintenance",
    "not_started",
    # Actions
    "check",
    "check_all",
    "close",
    "retry",
    "download",
    "more_options",
    "settings",
    "edit",
    "add",
    # Content types
    "topic",
    "form",
    "course_part",
    # User/system
    "user",
    "cohort",
    "notifications",
    "achievement",
    "loading",
    # Data display
    "sort_asc",
    "sort_desc",
    "sort_neutral",
    "boolean_true",
    "boolean_false",
    "search",
    "filter",
    # Trends
    "trend_up",
    "trend_down",
    # Deadlines
    "deadline",
    # Commerce
    "price",
    # Misc
    "sentiment_good",
    "sentiment_bad",
    "unknown",
    "star",
    "notes",
    "course",
}
