# Generated by Django 6.0.4 on 2026-08-23 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('freedom_ls_content_engine', '0014_course_table_of_contents_in_development'),
        ('freedom_ls_organisations', '0002_organisation_is_default_and_more'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='freedom_ls_organisations.organisation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='CohortCourseRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='freedom_ls_learner_management.cohort')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_registrations', to='freedom_ls_content_engine.course')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='CohortDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('is_hard_deadline', models.BooleanField(default=True)),
                ('cohort_course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='freedom_ls_learner_management.cohortcourseregistration')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='freedom_ls_organisations.organisation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CohortMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom_ls_learner_management.cohort')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom_ls_learner_management.learner')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerCourseRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_registrations', to='freedom_ls_content_engine.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom_ls_learner_management.learner')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('is_hard_deadline', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('learner_course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='freedom_ls_learner_management.learnercourseregistration')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='freedom_ls_content_engine.course')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recommended courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCohortDeadlineOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('is_hard_deadline', models.BooleanField(default=True)),
                ('cohort_course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_overrides', to='freedom_ls_learner_management.cohortcourseregistration')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom_ls_learner_management.learner')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('site_id', 'organisation', 'name'), name='unique_cohort_name_per_site'),
        ),
        migrations.AddConstraint(
            model_name='cohortcourseregistration',
            constraint=models.UniqueConstraint(fields=('site_id', 'collection', 'cohort'), name='unique_cohort_course_registration'),
        ),
        migrations.AddConstraint(
            model_name='cohortdeadline',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('cohort_course_registration', 'content_type', 'object_id'), name='unique_cohort_deadline_per_item'),
        ),
        migrations.AddConstraint(
            model_name='learner',
            constraint=models.UniqueConstraint(fields=('user', 'organisation'), name='unique_learner_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='cohortmembership',
            constraint=models.UniqueConstraint(fields=('learner', 'cohort'), name='unique_learner_cohort_membership'),
        ),
        migrations.AddConstraint(
            model_name='learnercourseregistration',
            constraint=models.UniqueConstraint(fields=('site_id', 'learner', 'collection'), name='unique_learner_course_registration'),
        ),
        migrations.AddConstraint(
            model_name='learnerdeadline',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('learner_course_registration', 'content_type', 'object_id'), name='unique_learner_deadline_per_item'),
        ),
        migrations.AddConstraint(
            model_name='usercohortdeadlineoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('cohort_course_registration', 'learner', 'content_type', 'object_id'), name='unique_user_cohort_override_per_item'),
        ),
    ]
