# Generated by Django 6.0.4 on 2026-08-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('freedom_ls_content_engine', '0017_alter_file_file'),
        ('freedom_ls_learner_management', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCohortDeadlineOverride',
            new_name='LearnerCohortDeadlineOverride',
        ),
        migrations.RemoveConstraint(
            model_name='cohortcourseregistration',
            name='unique_cohort_course_registration',
        ),
        migrations.RemoveConstraint(
            model_name='learnercohortdeadlineoverride',
            name='unique_user_cohort_override_per_item',
        ),
        migrations.RemoveConstraint(
            model_name='learnercourseregistration',
            name='unique_learner_course_registration',
        ),
        migrations.RenameField(
            model_name='cohortcourseregistration',
            old_name='collection',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='learnercourseregistration',
            old_name='collection',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='recommendedcourse',
            old_name='collection',
            new_name='course',
        ),
        migrations.AddConstraint(
            model_name='cohortcourseregistration',
            constraint=models.UniqueConstraint(fields=('site_id', 'course', 'cohort'), name='unique_cohort_course_registration'),
        ),
        migrations.AddConstraint(
            model_name='learnercohortdeadlineoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('cohort_course_registration', 'learner', 'content_type', 'object_id'), name='unique_learner_cohort_override_per_item'),
        ),
        migrations.AddConstraint(
            model_name='learnercourseregistration',
            constraint=models.UniqueConstraint(fields=('site_id', 'learner', 'course'), name='unique_learner_course_registration'),
        ),
    ]
