# Generated by Django 6.0.4 on 2026-09-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_learner_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnercourseregistration',
            name='self_registered',
            field=models.BooleanField(default=False, help_text='The learner registered themselves rather than being registered by staff.'),
        ),
    ]
