# Generated by Django 6.0.4 on 2026-08-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('freedom_ls_content_engine', '0018_activity_created_at_activity_updated_at_and_more'),
        ('freedom_ls_learner_management', '0003_cohort_created_at_cohort_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortcourseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohort_registrations', to='freedom_ls_content_engine.course'),
        ),
        migrations.AlterField(
            model_name='cohortdeadline',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='learnercohortdeadlineoverride',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='learnercourseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_registrations', to='freedom_ls_content_engine.course'),
        ),
        migrations.AlterField(
            model_name='learnerdeadline',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
