# Generated by Django 6.0.4 on 2026-09-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_learner_management', '0003_organisationmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'permissions': [('download_cohort_report', 'Can download cohort report')]},
        ),
        migrations.AlterModelOptions(
            name='learner',
            options={'permissions': [('bulk_manage_learners', 'Can bulk manage learners')]},
        ),
    ]
