# Generated by Django 5.2.9 on 2026-03-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_student_management', '0004_studentcohortdeadlineoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cellphone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
