# Generated by Django 6.0.4 on 2026-10-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_learner_management', '0004_alter_cohort_options_alter_learner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
