# Generated by Django 6.0.4 on 2026-08-28 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0019_alter_activity_unique_together_and_more'),
        ('freedom_ls_learner_management', '0004_alter_cohortcourseregistration_course_and_more'),
        ('freedom_ls_organisations', '0005_organisation_created_at_organisation_updated_at'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cohort',
            name='unique_cohort_name_per_site',
        ),
        migrations.RemoveConstraint(
            model_name='cohortcourseregistration',
            name='unique_cohort_course_registration',
        ),
        migrations.RemoveConstraint(
            model_name='learner',
            name='unique_learner_per_organisation',
        ),
        migrations.RemoveConstraint(
            model_name='learnercourseregistration',
            name='unique_learner_course_registration',
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('site', 'organisation', 'name'), name='unique_cohort_name_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='cohortcourseregistration',
            constraint=models.UniqueConstraint(fields=('site', 'course', 'cohort'), name='unique_cohort_course_registration'),
        ),
        migrations.AddConstraint(
            model_name='learner',
            constraint=models.UniqueConstraint(fields=('site', 'user', 'organisation'), name='unique_learner_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='learnercourseregistration',
            constraint=models.UniqueConstraint(fields=('site', 'learner', 'course'), name='unique_learner_course_registration'),
        ),
    ]
