# Generated by Django 5.2.9 on 2026-03-07 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_student_management', '0012_alter_usercourseregistration_collection'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cohortmembership',
            constraint=models.UniqueConstraint(fields=('user', 'cohort'), name='unique_user_cohort_membership'),
        ),
    ]
