# Generated by Django 6.0.4 on 2026-08-11 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_content_engine', '0014_course_table_of_contents_in_development'),
        ('freedom_ls_organisations', '0001_initial'),
        ('freedom_ls_student_management', '0014_cohort_organisation_and_more'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cohort',
            name='unique_cohort_name_per_site',
        ),
        migrations.RemoveConstraint(
            model_name='usercourseregistration',
            name='unique_user_course_registration',
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('site_id', 'organisation', 'name'), name='unique_cohort_name_per_site'),
        ),
        migrations.AddConstraint(
            model_name='usercourseregistration',
            constraint=models.UniqueConstraint(fields=('site_id', 'organisation', 'collection', 'user'), name='unique_user_course_registration'),
        ),
    ]
