# Generated by Django 5.2.8 on 2025-12-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcollection',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
