# Generated by Django 5.2.8 on 2025-12-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
