# Generated by Django 5.2.8 on 2025-11-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0002_add_category_to_form_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='strategy',
            field=models.CharField(choices=[('CATEGORY_VALUE_SUM', 'Category Value Sum'), ('QUIZ', 'Quiz')], max_length=50),
        ),
    ]
