# Generated by Django 5.2.8 on 2025-11-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0003_alter_form_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcollection',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description', null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description', null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description', null=True),
        ),
    ]
