# Generated by Django 5.2.8 on 2025-12-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0004_alter_activity_options_form_quiz_show_incorrect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formquestion',
            name='correct',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
