# Generated by Django 5.2.8 on 2025-11-25 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0004_contentcollection_description_form_description_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Relative path to the source file', max_length=500)),
                ('meta', models.JSONField(blank=True, help_text='Optional metadata as key-value pairs', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Optional list of tags', null=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=500)),
                ('content', models.TextField(blank=True, help_text='Markdown content', null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'unique_together': {('site', 'slug')},
            },
        ),
    ]
