# Generated by Django 5.2.8 on 2025-11-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
