# Generated by Django 5.2.8 on 2025-12-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0006_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcollection',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contentcollection',
            name='collection_type',
            field=models.CharField(blank=True, choices=[('COURSE', 'Course')], max_length=50, null=True),
        ),
    ]
