"""E2E tests for DataTablePanel HTMX swap behaviour.

These tests assert that HTMX-driven sort and pagination swaps inside a
``DataTablePanel`` do not nest panel ``<section>`` wrappers in the live DOM:
a sort or page click must get back the panel's region, never the whole panel,
or the browser places a second frame inside the first on every swap.
"""

from __future__ import annotations

import re

import pytest
import pytest_django.live_server_helper
from playwright.sync_api import Page, expect

from django.contrib.sites.models import Site

from ..conftest import _make_stub
from ..stub_panels import StubDataTable
from .assertions import expect_no_nested_panel

PAGE_SIZE = StubDataTable.page_size


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_data_table_sort_does_not_nest_panel_wrappers(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    """Clicking the sort header on a panel-rendered DataTable should swap the
    table contents without adding a second ``<section>`` wrapper inside the
    panel."""
    rows = [_make_stub(name=f"row-{i:02d}") for i in range(3)]
    pk = rows[0].pk

    page.goto(f"{live_server.url}/test-panel/framework/stubs/{pk}/")
    expect_no_nested_panel(page)

    # Three sort clicks: the original bug compounded a new <section> wrapper on
    # each swap, so the third click is the one that exposes the regression
    # most obviously.
    sort_link = page.get_by_role("link", name="Name")
    for _ in range(3):
        sort_link.click()
        expect_no_nested_panel(page)


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_data_table_pagination_does_not_nest_panel_wrappers(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    rows = [_make_stub(name=f"row-{i:02d}") for i in range(PAGE_SIZE + 2)]
    pk = rows[0].pk

    page.goto(f"{live_server.url}/test-panel/framework/stubs/{pk}/")
    expect_no_nested_panel(page)

    page.get_by_role("link", name="2").first.click()
    expect_no_nested_panel(page)

    page.get_by_role("link", name="1").first.click()
    expect_no_nested_panel(page)


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_pagination_preserves_sort_param_through_clicks(
    live_server,
    live_server_site,
    page: Page,
) -> None:
    """Sorting then paginating must keep ``stubs-sort=name`` in the request
    URL — proves sort state round-trips through pagination clicks under the
    list's own table key, alongside ``stubs-page``."""
    [_make_stub(name=f"row-{i:02d}") for i in range(PAGE_SIZE + 2)]

    page.goto(f"{live_server.url}/test-panel/framework/stubs/")

    # Sort first. HTMX doesn't push the URL, so wait on the rendered
    # pagination link's href instead — it's regenerated by the server with
    # the sort param baked in.
    page.get_by_role("link", name="Name").click()
    page2_link = page.get_by_role("link", name="2").first
    expect(page2_link).to_have_attribute("href", re.compile(r"stubs-sort=name"))
    expect(page2_link).to_have_attribute("href", re.compile(r"stubs-page=2"))


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_list_view_data_table_swaps_keep_single_container(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    """The list page is a panel too, so its swaps keep one frame."""
    [_make_stub(name=f"row-{i:02d}") for i in range(PAGE_SIZE + 2)]

    page.goto(f"{live_server.url}/test-panel/framework/stubs/")

    expect(page.locator("[data-panel]")).to_have_count(1)
    expect_no_nested_panel(page, name="")

    page.get_by_role("link", name="Name").click()
    # HTMX swap-only requests don't push the URL, so wait on the rendered
    # pagination link to confirm the swap landed.
    page2_link = page.get_by_role("link", name="2").first
    expect(page2_link).to_have_attribute("href", re.compile(r"sort=name"))
    expect(page2_link).to_have_attribute("href", re.compile(r"stubs-page=2"))
    expect(page.locator("[data-panel]")).to_have_count(1)
    expect_no_nested_panel(page, name="")


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_nested_table_pushes_page_url(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    """Clicking page 2 of a table nested two levels down (a tab holding a
    stack of two tables) pushes the tab's own URL, never the panel's."""
    stub = _make_stub(name="row-00")
    [_make_stub(name=f"row-{i:02d}") for i in range(1, PAGE_SIZE + 2)]

    page.goto(f"{live_server.url}/test-panel/framework/stubs/{stub.pk}/__tabs/pair")

    page.locator("#a-table").get_by_role("link", name="2").first.click()

    expect(page).to_have_url(re.compile(r"__tabs/pair\?a-page=2$"))
    expect(page).not_to_have_url(re.compile(r"__panels"))


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_back_after_sort_restores_matching_table(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    """Sorting pushes ``stubs-sort`` into history; paging further pushes
    ``stubs-page`` too. Going back must restore the sorted-but-unpaged state,
    in both the address bar and the rendered table."""
    [_make_stub(name=f"row-{i:02d}") for i in range(PAGE_SIZE + 2)]

    page.goto(f"{live_server.url}/test-panel/framework/stubs/")

    page.get_by_role("link", name="Name").click()
    page.get_by_role("link", name="2").first.click()
    expect(page).to_have_url(re.compile(r"stubs-page=2"))

    page.go_back()

    expect(page).to_have_url(re.compile(r"stubs-sort=name"))
    expect(page).not_to_have_url(re.compile(r"stubs-page"))
    first_row = page.locator("#stubs-table tbody tr").first
    expect(first_row).to_contain_text("row-00")


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_search_narrows_table_after_sort_is_active(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    """Once a sort is active, the sort's hidden input renders before the
    search box in the form. Typing into the search box must still fire the
    debounced htmx search request and narrow the table."""
    [_make_stub(name=f"row-{i:02d}") for i in range(3)]

    page.goto(f"{live_server.url}/test-panel/framework/stubs/")

    page.get_by_role("link", name="Name").click()
    # Wait for the sort's own htmx swap to land, not just for the row count
    # (which is already 3 before the swap, since the table only has 3 rows
    # either way). The hidden `stubs-sort` input only exists once a sort is
    # active — that's what pushes the search box out of first place in the
    # form, and it's the reliable signal the new toolbar markup is in place.
    expect(page.locator("#stubs-search input[name='stubs-sort']")).to_have_count(1)

    page.locator("#stubs-q").fill("row-01")

    rows = page.locator("#stubs-table tbody tr")
    expect(rows).to_have_count(1)
    expect(rows.first).to_contain_text("row-01")


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_focus_moves_to_table_anchor_after_swap(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    """A sort click swaps the table region; the reader's focus should land on
    the table's own anchor, not stay behind on the removed sort link."""
    [_make_stub(name=f"row-{i:02d}") for i in range(3)]

    page.goto(f"{live_server.url}/test-panel/framework/stubs/")

    page.get_by_role("link", name="Name").click()

    anchor = page.locator("#stubs-table [data-table-anchor]")
    expect(anchor).to_be_focused()


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_search_swap_keeps_focus_and_typing_in_search_box(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    """A reader who pauses mid-search and carries on typing must not lose
    characters: the search swap leaves focus in the search box instead of
    moving it to the table anchor."""
    [_make_stub(name=f"row-{i:02d}") for i in range(3)]

    page.goto(f"{live_server.url}/test-panel/framework/stubs/")

    search = page.locator("#stubs-q")
    search.click()
    search.press_sequentially("row-0")
    rows = page.locator("#stubs-table tbody tr")
    expect(page).to_have_url(re.compile(r"stubs-q=row-0"))
    # The URL updates on htmx:afterSwap, but the swapped-in form's search
    # trigger is only attached when htmx settles (~20ms later); a keystroke
    # in between fires no request. Wait for settle so the next one does.
    expect(page.locator(".htmx-added")).to_have_count(0)

    page.keyboard.type("1")

    expect(page.locator("#stubs-q")).to_have_value("row-01")
    expect(page.locator("#stubs-q")).to_be_focused()
    expect(rows).to_have_count(1)
    expect(rows.first).to_contain_text("row-01")


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_filter_sort_sheet_stays_closed_on_desktop(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    """The mobile filter & sort sheet must not open as a docked panel on
    desktop, where opening it would pull focus into a hidden dialog on every
    table swap."""
    [_make_stub(name=f"row-{i:02d}") for i in range(3)]

    page.goto(f"{live_server.url}/test-panel/framework/stubs/")
    sheet = page.locator("#stubs-sheet")
    expect(sheet).to_have_count(1)
    expect(sheet).not_to_have_attribute("open", re.compile(".*"))

    page.get_by_role("link", name="Name").click()
    expect(page).to_have_url(re.compile(r"stubs-sort=name"))
    expect(page.locator("#stubs-sheet")).not_to_have_attribute("open", re.compile(".*"))


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_paging_one_table_keeps_sibling_page_in_url(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    """Table a's links were rendered before table b was paged; paging a
    afterwards must keep b's page in the address bar and across a reload."""
    stubs = [_make_stub(name=f"row-{i:02d}") for i in range(PAGE_SIZE + 5)]

    page.goto(f"{live_server.url}/test-panel/framework/stubs/{stubs[0].pk}/__tabs/pair")

    page.locator("#b-table").get_by_role("link", name="2", exact=True).click()
    expect(page).to_have_url(re.compile(r"b-page=2"))
    page.locator("#a-table").get_by_role("link", name="2", exact=True).click()
    expect(page).to_have_url(re.compile(r"a-page=2"))
    expect(page).to_have_url(re.compile(r"b-page=2"))

    page.reload()
    expect(page.locator("#a-table")).to_contain_text(f"row-{PAGE_SIZE:02d}")
    expect(page.locator("#b-table")).to_contain_text(f"row-{PAGE_SIZE:02d}")
