"""E2E tests for DataTablePanel HTMX swap behaviour.

These tests assert that HTMX-driven sort and pagination swaps inside a
``DataTablePanel`` do not nest panel ``<section>`` wrappers in the live DOM:
a sort or page click must get back the panel's region, never the whole panel,
or the browser places a second frame inside the first on every swap.
"""

from __future__ import annotations

import re

import pytest
import pytest_django.live_server_helper
from playwright.sync_api import Page, expect

from django.contrib.sites.models import Site

from ..conftest import _make_stub
from ..stub_panels import StubDataTable
from .assertions import expect_no_nested_panel

PAGE_SIZE = StubDataTable.page_size


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_data_table_sort_does_not_nest_panel_wrappers(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    """Clicking the sort header on a panel-rendered DataTable should swap the
    table contents without adding a second ``<section>`` wrapper inside the
    panel."""
    rows = [_make_stub(name=f"row-{i:02d}") for i in range(3)]
    pk = rows[0].pk

    page.goto(f"{live_server.url}/test-panel/framework/stubs/{pk}/")
    expect_no_nested_panel(page)

    # Three sort clicks: the original bug compounded a new <section> wrapper on
    # each swap, so the third click is the one that exposes the regression
    # most obviously.
    sort_link = page.get_by_role("link", name="Name")
    for _ in range(3):
        sort_link.click()
        expect_no_nested_panel(page)


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_data_table_pagination_does_not_nest_panel_wrappers(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    rows = [_make_stub(name=f"row-{i:02d}") for i in range(PAGE_SIZE + 2)]
    pk = rows[0].pk

    page.goto(f"{live_server.url}/test-panel/framework/stubs/{pk}/")
    expect_no_nested_panel(page)

    page.get_by_role("link", name="2").first.click()
    expect_no_nested_panel(page)

    page.get_by_role("link", name="1").first.click()
    expect_no_nested_panel(page)


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_pagination_preserves_sort_param_through_clicks(
    live_server,
    live_server_site,
    page: Page,
) -> None:
    """Sorting then paginating must keep ``sort=name`` in the request URL —
    proves the new ``pagination_suffix`` template tag round-trips query
    params through pagination clicks, not just renders them in a given
    context."""
    [_make_stub(name=f"row-{i:02d}") for i in range(PAGE_SIZE + 2)]

    page.goto(f"{live_server.url}/test-panel/framework/stubs/")

    # Sort first. HTMX doesn't push the URL, so wait on the rendered
    # pagination link's href instead — it's regenerated by the server with
    # the sort param baked in.
    page.get_by_role("link", name="Name").click()
    page2_link = page.get_by_role("link", name="2").first
    expect(page2_link).to_have_attribute("href", re.compile(r"sort=name"))
    expect(page2_link).to_have_attribute("href", re.compile(r"page=2"))


@pytest.mark.playwright
@pytest.mark.django_db(transaction=True)
def test_list_view_data_table_swaps_keep_single_container(
    live_server: pytest_django.live_server_helper.LiveServer,
    live_server_site: Site,
    page: Page,
) -> None:
    """The list page is a panel too, so its swaps keep one frame."""
    [_make_stub(name=f"row-{i:02d}") for i in range(PAGE_SIZE + 2)]

    page.goto(f"{live_server.url}/test-panel/framework/stubs/")

    expect(page.locator("[data-panel]")).to_have_count(1)
    expect_no_nested_panel(page, name="")

    page.get_by_role("link", name="Name").click()
    # HTMX swap-only requests don't push the URL, so wait on the rendered
    # pagination link to confirm the swap landed.
    page2_link = page.get_by_role("link", name="2").first
    expect(page2_link).to_have_attribute("href", re.compile(r"sort=name"))
    expect(page.locator("[data-panel]")).to_have_count(1)
    expect_no_nested_panel(page, name="")
