#!/usr/bin/env bash
# claude.sh — Generated by the django-stack (ds) plugin init
# Launches Claude Code with the django-stack plugin loaded.
#
# Each plugin's init adds its own `--plugin-dir` line above "$@"; this file may
# therefore carry more than one such line if other plugins are also installed.

PLUGINS_ROOT="__PLUGINS_ROOT__"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CLAUDE_PLUGINS_LOADED=1 claude \
  --plugin-dir "$SCRIPT_DIR/$PLUGINS_ROOT/claude_plugins/django-stack" \
  "$@"
