# Generated by Django 5.2.9 on 2026-03-07 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('freedom_ls_role_based_permissions', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objectroleassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='siteroleassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='systemroleassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='objectroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id', 'role'), name='unique_object_role_per_user'),
        ),
        migrations.AddConstraint(
            model_name='siteroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'site', 'role'), name='unique_site_role_per_user'),
        ),
        migrations.AddConstraint(
            model_name='systemroleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_system_role_per_user'),
        ),
    ]
