# Generated by Django 6.0.4 on 2026-09-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_role_based_permissions', '0002_rename_educator_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectroleassignment',
            options={'permissions': [('assign_organisation_admin', 'Can grant or remove the organisation_admin role'), ('assign_cohort_admin', 'Can grant or remove the cohort_admin role'), ('assign_cohort_viewer', 'Can grant or remove the cohort_viewer role')]},
        ),
        migrations.AlterModelOptions(
            name='siteroleassignment',
            options={'permissions': [('assign_site_admin', 'Can grant or remove the site_admin role')]},
        ),
    ]
