# Generated by Django 6.0.4 on 2026-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom_ls_role_based_permissions', '0002_alter_objectroleassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectroleassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='siteroleassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='systemroleassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
