# Generated by Django 5.2.7 on 2025-11-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0003_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='short_name',
        ),
    ]
