# Generated by Django 5.2.7 on 2025-11-07 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_engine', '0002_add_category_to_form_page'),
        ('sites', '0002_alter_domain_unique'),
        ('student_management', '0004_remove_student_email_remove_student_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortCourseRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='student_management.cohort')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_registrations', to='content_engine.contentcollection')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'collection', 'cohort'), name='unique_cohort_course_registration')],
            },
        ),
        migrations.CreateModel(
            name='StudentCourseRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='content_engine.contentcollection')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='student_management.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('site_id', 'collection', 'student'), name='unique_student_course_registration')],
            },
        ),
    ]
